### ISSUE TITLE
Hello i get this problem: No such file or directory: 'cookie/token.log'

### ISSUE THREAD

**Issue by Brynjar98** [CiKu370/OSIF#27]
After i type in my fb username and password i get this error. 

[*] Generate access token 
Traceback (most recent call last):
  File "osif.py", line 1251, in <module>
    main()
  File "osif.py", line 971, in main
    id()
  File "osif.py", line 180, in id
    get(data)
  File "osif.py", line 154, in get
    b = open('cookie/token.log','w')
IOError: [Errno 2] No such file or directory: 'cookie/token.log'

**Comment by NightSling** [comment]
r u using latest version?
and Make sure u have Installed Requirements And According to it U DOnt have cokkie/token.log files Have u deleted anything?

**Comment by Brynjar98** [comment]
> r u using latest version?
> and Make sure u have Installed Requirements And According to it U DOnt have cokkie/token.log files Have u deleted anything?

Yes i believe so. I have not deleted anything.

**Comment by NightSling** [comment]
Try to run as sudo and clone it on /dev/shm
